#!/bin/bash
# gets a fresh Pharo 3.0 image and loads Bytes

echo "Downloading Pharo 3.0 and a VM ..."
rm pharo
rm pharo-ui
rm -rf pharo-vm
wget -O- get.pharo.org/30+vm | bash

echo "Opening Pharo to load Bytes ..."
./pharo-ui Pharo.image BytesLoader.st

echo "Ready!"
